twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        shop_settings: '%shop_settings%'